version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://username:password@db:5432/tododb
    depends_on:
      - db
