version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: danielrowin
      POSTGRES_PASSWORD: Chelsea2021
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://danielrowin:Chelsea2021@db:5432/tododb
    depends_on:
      - db

